### ISSUE TITLE
P2-Compuertas-lógicas-Equipo-Eduardo-Tomas-1AS

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/compuertas-logicas-team-eduardo-tomas-1as#1]
[practica 2 matematicas V.pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-team-eduardo-tomas-1as/files/7731105/practica.2.matematicas.V.pdf)

**Comment by yaritzaov123** [comment]
Portada: 25% cumple con los criterios a evaluar 
Procedimiento: 25 %, contiene las descripciones requeridas y el objetivo 
Figuras ilustraciones y fotografías: 25% 
Resultados y conclusiones: 25% tiene los resultados y conclusiones 
También les falta estructurar mejor el contenido 
calificacion = 100/100 = 30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado
